spring.application.name=ecom-application
server.port= 8088
#spring.h2.console.enabled= true
#spring.datasource.url=jdbc:h2:mem:test
management.endpoints.web.exposure.include=beans
management.endpoint.health.show-details=always
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomdb?options=-c%20TimeZone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.username= username
spring.datasource.password= password
spring.jpa.database= POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect



